# -*- coding: utf-8 -*-
"""nasdaq_M5_prophet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186SoRijJxQ8OuXsjGLJPHMgr076V6IEQ
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from prophet import Prophet

url=('https://raw.githubusercontent.com/tomekbiel/MT4_Trading_System/refs/heads/master/data/historical/US.100%2B/M5/US.100%2B_M5.csv')
df = pd.read_csv(url)
df

df1=pd.to_datetime(df.time)
#nsq100futures_dataframe=pd.to_datetime(df.Date)
#nsq100futures_dataframe=df.to_csv('nsq100f')

df=df.drop('time',axis=1)
df
df.info()

df1.info()

df=pd.concat([df1,df],axis=1)
df

df.columns
df2=df.drop([ 'open', 'high', 'low',  'tick_volume', 'spread','real_volume', 'volume'],axis=1)
df2.info()

#df2=df2.drop(['Vol.','Change %'],axis=1)
df.to_csv('cleaned_nsq')

df2

#data = df2.Price.replace(',',)

df2 = df2.rename(columns={'time': 'ds', 'close': 'y'})

df2.info()

#data
df2.y = df2.y.replace(' , ', '', regex=True).astype(float)
#df2.y.lstrip(',')
df2.info()

df2['y'] = df2['y'].astype("string")
df2
df2.info()

df2['y']=df2['y'].str.replace(',','')
#df2.y = df2.y.replace(' , ', '', regex=True)
df2

df2.y=df2.y.astype('float')
df2.info()

m = Prophet()
m.fit(df2)

future = m.make_future_dataframe(periods=365)
future.tail()

df2.head(10)

forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(20)

fig1 = m.plot(forecast)

fig2 = m.plot_components(forecast)

from prophet.plot import plot_plotly, plot_components_plotly

plot_plotly(m, forecast)

plot_components_plotly(m, forecast)